data_eizo <- read.csv('../stimuli/images/chrom_stats_eizo.csv')
data_oled <- read.csv('../stimuli/images/chrom_stats_oled.csv')
par(mfrow=c(1,3), pty="s")
plot(data_oled$rmc_l, data_oled$rsd_l)
points(data_eizo$rmc_l, data_eizo$rsd_l, col="blue")
plot(data_oled$rmc_m, data_oled$rsd_m)
points(data_eizo$rmc_m, data_eizo$rsd_m, col="blue")
plot(data_oled$rmc_s, data_oled$rsd_s)
points(data_eizo$rmc_s, data_eizo$rsd_s, col="blue")