clear all; close all; clc;

fns = dir('../data/*.mat');

monxyY = csvread('../../calibration/oled_chroma.csv');
monxyz = xyY2XYZ(monxyY);

ims = dir('../stimuli/images/color_diff*.png');

fh = fopen('../data/all_obs_data_together.csv', 'w');

fprintf(fh, 'sub_id,trial,img,illum,body,highlow,l,a,b,lrc,redness,wpld,wprg,wpyv,gwld,gwrg,gwyv,gwl,gwa,gwb,hv,mean_cone_l,mean_cone_m,mean_cone_s,sd_cone_l,sd_cone_m,sd_cone_s,mask,bkg\n');

for fc = 1:length(fns)
    fn = fns(fc).name;
    load(['../data/' fn], 'data', 'subID', 'trialOrder');

    fnparts = strsplit(fn, '_');
    if strcmp(fnparts{end}, 'k.mat')
        bkg = 'black';
    elseif strcmp(fnparts{end}, 'w.mat')
        bkg = 'white';
    else
        bkg = 'gray';
    end

    for tc = 1:size(ims, 1)
        fparts = strsplit(ims(tc).name, '_');
        if strcmp(fparts{end}, 'lighter.png')
            hilo = 1;
        else
            hilo = 0;
        end
        illum = fparts{5};
        body = fparts{9};

        idxs = find(trialOrder == tc);
        c = 1;
        for x = idxs
            stats = readtable(['../stimuli/images/' ims(tc).name '_masked.csv']);

            lab = real(rgb2labRob(squeeze(data(x, 1, :))', monxyz));
            if any(squeeze(data(x, 1, :)) > 1)
                subID
            end

            for mc = 1:size(stats, 1)
                mask_name = stats.mask(mc);

                fprintf(fh, [subID ',' ...
                    num2str(c) ',' ...
                    num2str(tc) ',' ...
                    illum ',' ...
                    body ',' ...
                    num2str(hilo) ',' ...
                    num2str(lab(1)) ',' ...
                    num2str(lab(2)) ',' ...
                    num2str(lab(3)) ',' ...
                    num2str(stats.lrc(mc)) ',' ...
                    num2str(stats.redness(mc)) ',' ...
                    num2str(stats.wpld(mc)) ',' ...
                    num2str(stats.wprg(mc)) ',' ...
                    num2str(stats.wpyv(mc)) ',' ...
                    num2str(stats.gwld(mc)) ',' ...
                    num2str(stats.gwrg(mc)) ',' ...
                    num2str(stats.gwyv(mc)) ',' ...
                    num2str(stats.gwl(mc)) ',' ...
                    num2str(stats.gwa(mc)) ',' ...
                    num2str(stats.gwb(mc)) ',' ...
                    num2str(stats.hv(mc)) ',' ...
                    num2str(stats.mean_cone_l(mc)) ',' ...
                    num2str(stats.mean_cone_m(mc)) ',' ...
                    num2str(stats.mean_cone_s(mc)) ',' ...
                    num2str(stats.sd_cone_l(mc)) ',' ...
                    num2str(stats.sd_cone_m(mc)) ',' ...
                    num2str(stats.sd_cone_s(mc)) ',' ...
                    mask_name{1} ',' ...
                    bkg '\n']);
            end

            c = c + 1;
        end
    end
end
fclose(fh);
